#Autor: nkumtan
#Date:Dec 22/200
#Description: playbook for patching
---
- name: Checking of running processes
  become: true
  hosts: all
  tasks:
  -  name: check the running processes
     shell: if ps -eaf | egrep 'httpd' | grep -v grep > /dev/null;then echo "process_running";else echo "process_not_running"; fi
     ignore_errors: true
     register: appr_proc_check
  -  debug: 
       msg="{{appr_proc_check.stdout}}"
  
  -  name: Decision point to start patching
     fail:
       msg="{{ inventory_hostname }} having running applications, please stop first then attempt patching"
     when: appr_proc_check.stdout == "process_running"
     #-  name: copy repos to the managed node
     #copy: 
     #src=/root/amzn2-core.repo 
       #dest=/etc/yum.repos.d/
  -  name: current kernel
     shell: uname -r
     register: curr_kernel
  -  name: initiating patching
     yum: 
       name=kernel  
       state=latest
     register: nkumac_out
  -  debug: msg="kernel updated"
     when: nkumac_out.rc == 0
     #-  name: checking reboot state
    #shell: kernel_new=$(rpm -qa --last kernel | head -1 | awk '{print $1}' | sed 's/kernel-//g'); kernel_now=$(uname -r); if [[ $kernel_new == $kernel_now ]]; then echo "reboot is needed"; else echo "reboot is not neede"; fi
     #ignore_error: true
     #register: reboot_check
     #-  debug: 
    # msg= '{{ reboot_check.stdout }}'


  -  name: reboot the servers
     shell: "shutdown -r y now"
     async: 1
     poll: 0
  -  name: wait for the system to come up
     wait_for:
       sleep: 1
  -  name: New kernel version
     shell: uname -r
     register: kernel_newk
  -  debug:
       msg="New kernel version is {{kernel_newk,stdout}} and old kernel version is {{curr_kernel.stdout}}"

